export type Big5Item = {
  id: number
  text: string
  trait: 'O' | 'C' | 'E' | 'A' | 'N'
  reverse?: boolean
}

export const BIG5_ITEMS: Big5Item[] = [
  { id: 1, text: "I am the life of the party.", trait: "E" },
  { id: 2, text: "I don't talk a lot.", trait: "E", reverse: true },
  { id: 3, text: "I feel comfortable around people.", trait: "E" },
  { id: 4, text: "I keep in the background.", trait: "E", reverse: true },
  { id: 5, text: "I start conversations.", trait: "E" },
  { id: 6, text: "I have little to say.", trait: "E", reverse: true },
  { id: 7, text: "I talk to a lot of different people at parties.", trait: "E" },
  { id: 8, text: "I don't like to draw attention to myself.", trait: "E", reverse: true },
  { id: 9, text: "I don't mind being the center of attention.", trait: "E" },
  { id: 10, text: "I am quiet around strangers.", trait: "E", reverse: true },
  { id: 11, text: "I feel little concern for others.", trait: "A", reverse: true },
  { id: 12, text: "I am interested in people.", trait: "A" },
  { id: 13, text: "I insult people.", trait: "A", reverse: true },
  { id: 14, text: "I sympathize with others' feelings.", trait: "A" },
  { id: 15, text: "I am not interested in other people's problems.", trait: "A", reverse: true },
  { id: 16, text: "I have a soft heart.", trait: "A" },
  { id: 17, text: "I am not really interested in others.", trait: "A", reverse: true },
  { id: 18, text: "I take time out for others.", trait: "A" },
  { id: 19, text: "I feel others' emotions.", trait: "A" },
  { id: 20, text: "I make people feel at ease.", trait: "A" },
  { id: 21, text: "I am always prepared.", trait: "C" },
  { id: 22, text: "I leave my belongings around.", trait: "C", reverse: true },
  { id: 23, text: "I pay attention to details.", trait: "C" },
  { id: 24, text: "I make a mess of things.", trait: "C", reverse: true },
  { id: 25, text: "I get chores done right away.", trait: "C" },
  { id: 26, text: "I often forget to put things back in their proper place.", trait: "C", reverse: true },
  { id: 27, text: "I like order.", trait: "C" },
  { id: 28, text: "I shirk my duties.", trait: "C", reverse: true },
  { id: 29, text: "I follow a schedule.", trait: "C" },
  { id: 30, text: "I am exacting in my work.", trait: "C" },
  { id: 31, text: "I get stressed out easily.", trait: "N" },
  { id: 32, text: "I am relaxed most of the time.", trait: "N", reverse: true },
  { id: 33, text: "I worry about things.", trait: "N" },
  { id: 34, text: "I seldom feel blue.", trait: "N", reverse: true },
  { id: 35, text: "I am easily disturbed.", trait: "N" },
  { id: 36, text: "I get upset easily.", trait: "N" },
  { id: 37, text: "I change my mood a lot.", trait: "N" },
  { id: 38, text: "I have frequent mood swings.", trait: "N" },
  { id: 39, text: "I get irritated easily.", trait: "N" },
  { id: 40, text: "I often feel blue.", trait: "N" },
  { id: 41, text: "I am full of ideas.", trait: "O" },
  { id: 42, text: "I am not interested in abstract ideas.", trait: "O", reverse: true },
  { id: 43, text: "I have a vivid imagination.", trait: "O" },
  { id: 44, text: "I have difficulty understanding abstract ideas.", trait: "O", reverse: true },
  { id: 45, text: "I am quick to understand things.", trait: "O" },
  { id: 46, text: "I use difficult words.", trait: "O" },
  { id: 47, text: "I spend time reflecting on things.", trait: "O" },
  { id: 48, text: "I am not interested in theoretical discussions.", trait: "O", reverse: true },
  { id: 49, text: "I have excellent ideas.", trait: "O" },
  { id: 50, text: "I do not have a good imagination.", trait: "O", reverse: true }
]
